version: '3'
services:
  airflow:
    build: ./airflow
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./airflow/.env
  scraping:
    build: ./scraping
    volumes:
      - myapp:/shared
  downloader:
    build: ./downloader
    volumes:
      - myapp:/shared
    env_file: ./downloader/.env
  spark:
    build: ./spark
    volumes:
      - myapp:/shared
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  myapp:
