version: '3'
services:
  airflow:
    build: 
      context: ./airflow
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  scraping:
    build:
      context: ./scraping
    volumes:
      - myapp:/shared
volumes:
  myapp: 
